spring:
  main.banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/fda
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: fda-container-managing
  cloud:
    loadbalancer.ribbon.enabled: false
server.port: 9091
logging:
  pattern.console: "%d %highlight(%-5level) %msg%n"
  level:
    root: warn
    at.: debug
eureka:
  instance.hostname: fda-discovery-server
  client.serviceUrl.defaultZone: http://${eureka.instance.hostname}:9090/eureka/