spring:
  main.banner-mode: off
  datasource:
    url: jdbc:postgresql://fda-metadata-db:5432/fda
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
  application:
    name: fda-query-service
  rabbitmq:
    host: fda-broker-service
    username: guest
    password: guest
  cloud:
    loadbalancer.ribbon.enabled: false
server.port: 9093
logging:
  pattern.console: "%d %highlight(%-5level) %msg%n"
  level:
    root: warn
    at.tuwien.: debug
eureka:
  instance.hostname: fda-query-service
  client.serviceUrl.defaultZone: http://fda-discovery-service:9090/eureka/
fda:
  gateway.endpoint: http://fda-gateway-service:9095
  ready.path: /ready