image: tmaier/docker-compose:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: docker

stages:
  - build # todo add more

before_script:
  - docker info
  - docker-compose version

docker-compose-build:
  stage: build
  script:
    - docker-compose build