before_script: 
  - "docker version"
  - "docker-compose version"
  - "mvn --version"

variables:
  HOSTALIASES: ./hosts
  DOCKER_TLS_CERTDIR: /certs

cache:
  paths: 
    - /root/.m2/repository/
    - /root/.npm/

image: "docker/compose:latest"

stages: 
  - build
  - test-frontend
  - test-backend
  - deploy

build-backend-maven:
  stage: build
  script:
    - "make build-backend-maven"

build-backend-docker:
  stage: build
  script:
    - make build-backend-docker

test-frontend:
  stage: test-frontend
  script:
    - make test-frontend
  artifacts:
    when: always
    paths:
      - "fda-ui/videos/*"
    expire_in: 1 week
  variables:
    CI_DEBUG_TRACE: "true"

test-backend-container:
  stage: test-backend
  script:
    - make test-backend-container
    - cat ./fda-container-service/report/target/site/jacoco-aggregate/index.html
  needs:
    - build-backend-maven
  dependencies:
    - build-backend-maven
  artifacts:
    when: always
    paths:
      - fda-container-service/rest-service/target/site/jacoco/jacoco.xml
      - fda-container-service/rest-service/target/site/jacoco/index.html
    reports:
      junit:
        - fda-container-service/rest-service/target/surefire-reports/TEST-*.xml

test-backend-database:
  stage: test-backend
  script:
    - mvn -f fda-database-service/pom.xml clean test verify
    - cat ./fda-database-service/report/target/site/jacoco-aggregate/index.html
  needs:
    - build-backend-maven
  dependencies:
    - build-backend-maven
  artifacts:
    when: always
    paths:
      - fda-database-service/rest-service/target/site/jacoco/jacoco.xml
      - fda-database-service/rest-service/target/site/jacoco/index.html
    reports:
      junit:
        - fda-database-service/rest-service/target/surefire-reports/TEST-*.xml

test-backend-discovery:
  stage: test-backend
  script:
    - mvn -f fda-discovery-service/pom.xml clean test verify
    - cat ./fda-discovery-service/report/target/site/jacoco-aggregate/index.html
  needs:
    - build-backend-maven
  dependencies:
    - build-backend-maven
  artifacts:
    when: always
    paths:
      - fda-discovery-service/rest-service/target/site/jacoco/jacoco.xml
      - fda-discovery-service/rest-service/target/site/jacoco/index.html
    reports:
      junit:
        - fda-discovery-service/rest-service/target/surefire-reports/TEST-*.xml

test-backend-gateway:
  stage: test-backend
  script:
    - mvn -f fda-gateway-service/pom.xml clean test verify
    - cat ./fda-gateway-service/report/target/site/jacoco-aggregate/index.html
  needs:
    - build-backend-maven
  dependencies:
    - build-backend-maven
  artifacts:
    when: always
    paths:
      - fda-gateway-service/rest-service/target/site/jacoco/jacoco.xml
      - fda-gateway-service/rest-service/target/site/jacoco/index.html
    reports:
      junit:
        - fda-gateway-service/rest-service/target/surefire-reports/TEST-*.xml

test-backend-query:
  stage: test-backend
  script:
    - mvn -f fda-query-service/pom.xml clean test verify
    - cat ./fda-query-service/report/target/site/jacoco-aggregate/index.html
  needs:
    - build-backend-maven
  dependencies:
    - build-backend-maven
  artifacts:
    when: always
    paths:
      - fda-query-service/rest-service/target/site/jacoco/jacoco.xml
      - fda-query-service/rest-service/target/site/jacoco/index.html
    reports:
      junit:
        - fda-query-service/rest-service/target/surefire-reports/TEST-*.xml

test-backend-table:
  stage: test-backend
  script:
    - mvn -f fda-table-service/pom.xml clean test verify
    - cat ./fda-table-service/report/target/site/jacoco-aggregate/index.html
  needs:
    - build-backend-maven
  dependencies:
    - build-backend-maven
  artifacts:
    when: always
    paths:
      - fda-table-service/rest-service/target/site/jacoco/jacoco.xml
      - fda-table-service/rest-service/target/site/jacoco/index.html
    reports:
      junit:
        - fda-table-service/rest-service/target/surefire-reports/TEST-*.xml

test-backend-citation:
  stage: test-backend
  script:
    - "ZENODO_API_KEY=${ZENODO_API_KEY} mvn -f fda-citation-service/pom.xml clean test verify"
    - cat ./fda-citation-service/report/target/site/jacoco-aggregate/index.html
  needs:
    - build-backend-maven
  dependencies:
    - build-backend-maven
  artifacts:
    when: always
    paths:
      - fda-citation-service/rest-service/target/site/jacoco/jacoco.xml
      - fda-citation-service/rest-service/target/site/jacoco/index.html
    reports:
      junit:
        - fda-citation-service/rest-service/target/surefire-reports/TEST-*.xml

deploy-registry:
  stage: deploy
  script:
    - make deploy
