image: docker/compose:latest

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker version

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build
  - test
  - deploy
  - production

build:
  stage: build
  script:
    - docker-compose down
    - docker-compose build

test:
  stage: test
  script:
    - echo "todo"

deploy:
  stage: deploy
  script:
    - echo "todo"
  only:
    - master

production:
  stage: production
  script:
    - echo "todo"
