image: docker:latest

services:
  - docker:dind

before_script:
  - docker version
  - cd ./fda-ui && git pull

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build
  - test
  - deploy
  - production

build:
  stage: build
  script:
    - docker build -t fda-discovery-server ./fda-discovery-server
    - docker build -t fda-gateway-service ./fda-gateway-service
    - docker build -t fda-database-managing-service ./fda-database-managing-service
    - docker build -t fda-container-managing-service ./fda-container-managing-service
    - docker build -t fda-query-service ./fda-query-service
    - docker build -t fda-analyse-service ./fda-analyse-service
    - docker build -t fda-ui ./fda-ui

test:
  stage: test
  script:
    - echo "todo"

deploy:
  stage: deploy
  script:
    - echo "todo"
  only:
    - master

production:
  stage: production
  script:
    - echo "todo"
