image: docker/compose:latest

services:
  - docker:18.09-dind

before_script:
  - docker version
  - docker-compose version

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build
  - test
  - deploy
  - production

build:
  stage: build
  script:
    - docker-compose down
    - docker-compose build

test:
  stage: test
  script:
    - echo "todo"

deploy:
  stage: deploy
  script:
    - echo "todo"
  only:
    - master

production:
  stage: production
  script:
    - echo "todo"
