image: docker:latest

before_script:
  - docker version

cache:
  paths:
    - /root/.m2/repository/

stages:
  - build
  - test
  - deploy
  - production

build:
  stage: build
  script:
    - docker build -t fda-container-managing-service ./fda-container-managing-service
    - docker build -t fda-gateway-service ./fda-gateway-service
    - echo "todo"

test:
  stage: test
  script:
    - echo "todo"

deploy:
  stage: deploy
  script:
    - echo "todo"
  only:
    - master

production:
  stage: production
  script:
    - echo "todo"
