image: docker/compose:latest

# until fda-ui is in repo it will not be built
before_script:
  - docker version
  - docker-compose version

cache:
  paths:
    - /root/.m2/repository/

stages:
  - build
  - test
  - deploy
  - production

build:
  stage: build
  script:
    - docker-compose down
    - docker-compose build fda-discovery-server fda-gateway-service fda-database-managing-service fda-container-managing-service fda-query-service fda-table-service fda-analyse-service

test:
  stage: test
  script:
    - echo "todo"

deploy:
  stage: deploy
  script:
    - echo "todo"
  only:
    - master

production:
  stage: production
  script:
    - echo "todo"
