--- 
before_script: 
  - "docker version"
  - "docker-compose version"
  - "mvn --version"

cache: 
  paths: 
    - /root/.m2/repository/
    - /root/.npm/

image: "docker/compose:latest"

stages: 
  - build
  - test

build:
  stage: build
  script:
    - "docker-compose build"

test-backend:
  stage: test
  script:
    - "docker-compose up -d fda-metadata-db-test"
    - "mvn -f fda-metadata-db/pom.xml clean install" # local maven2 repository
    - "mvn -f fda-container-service/pom.xml clean test"
    - "mvn -f fda-database-service/pom.xml clean test"
    - "mvn -f fda-discovery-service/pom.xml clean test"
    - "mvn -f fda-gateway-service/pom.xml clean test"
    - "mvn -f fda-query-service/pom.xml clean test"
    - "mvn -f fda-table-service/pom.xml clean test"
    - "docker-compose down fda-metadata-db-test"

test-frontend:
  stage: test
  script: 
    - "echo \"todo\""

variables: 
  DOCKER_TLS_CERTDIR: /certs

