--- 
before_script: 
  - "docker version"
  - "docker-compose version"
  - "mvn --version"
build: 
  script: 
    - "docker-compose build"
  stage: build
cache: 
  paths: 
    - /root/.m2/repository/
    - /root/.npm/
image: "docker/compose:latest"
stages: 
  - build
  - test
test-backend: 
  script: 
    - "mvn -f fda-container-service/pom.xml clean test"
    - "mvn -f fda-table-service/pom.xml clean test"
    - "mvn -f fda-database-service/pom.xml clean test"
    - "mvn -f fda-discovery-server/pom.xml clean test"
    - "mvn -f fda-query-service/pom.xml clean test"
  stage: test
test-frontend: 
  script: 
    - "echo \"todo\""
  stage: test
variables: 
  DOCKER_TLS_CERTDIR: /certs

