image: docker/compose:latest

# until fda-ui is in repo it will not be built
before_script:
  - docker version
  - docker-compose version
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

cache:
  paths:
    - /root/.m2/repository/

variables:
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build
  - test
  - deploy
  - production

build:
  stage: build
  script:
    - docker-compose down
    - docker-compose build

test-backend:
  stage: test
  script:
    - echo "todo"

test-frontend:
  stage: test
  script:
    - echo "todo"

deploy:
  stage: deploy
  script:
    - docker build -t $CI_REGISTRY/fda-analyse-service:latest ./fda-analyse-service
    - docker push $CI_REGISTRY/fda-analyse-service:latest
    - docker build -t $CI_REGISTRY/fda-discovery-server:latest ./fda-discovery-server
    - docker push $CI_REGISTRY/fda-discovery-server:latest
    - docker build -t $CI_REGISTRY/fda-gateway-service:latest ./fda-gateway-service
    - docker push $CI_REGISTRY/fda-gateway-service:latest
    - docker build -t $CI_REGISTRY/fda-database-managing-service:latest ./fda-database-managing-service
    - docker push $CI_REGISTRY/fda-database-managing-service:latest
    - docker build -t $CI_REGISTRY/fda-container-managing-service:latest ./fda-container-managing-service
    - docker push $CI_REGISTRY/fda-container-managing-service:latest
    - docker build -t $CI_REGISTRY/fda-query-service:latest ./fda-query-service
    - docker push $CI_REGISTRY/fda-query-service:latest
    - docker build -t $CI_REGISTRY/fda-table-service:latest ./fda-table-service
    - docker push $CI_REGISTRY/fda-table-service:latest
    - docker build -t $CI_REGISTRY/fda-ui:latest ./fda-ui
    - docker push $CI_REGISTRY/fda-ui:latest
    - docker logout $CI_REGISTRY
  only:
    - dev
    - master

production:
  image: junte/ssh-agent
  stage: production
  variables:
    SSH_PRIVATE_KEY: $SSH_PROD_PRIVATE_KEY
  script:
    - scp docker-compose.prod.yml $PROD_CRED:~/deployment
    - ssh $PROD_CRED "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - ssh $PROD_CRED "docker-compose --file ~/deployment/docker-compose.prod.yml pull"
    - ssh $PROD_CRED "docker-compose --file ~/deployment/docker-compose.prod.yml down"
    - ssh $PROD_CRED "docker-compose --file ~/deployment/docker-compose.prod.yml up -d"
