version: "3.6"

volumes:
  fda-metadata-db-data:

services:

  fda-metadata-db:
    restart: always
    container_name: fda-metadata-db
    hostname: fda-metadata-db
    image: postgres:13-alpine
    volumes:
      - fda-metadata-db-data:/var/lib/postgresql/data
    network_mode: bridge
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fda



  fda-discovery-server:
    restart: always
    container_name: fda-discovery-server
    hostname: fda-discovery-server
    build: ./fda-discovery-server
    image: fda-discovery-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
    network_mode: bridge
    ports:
      - 9090:9090

  fda-gateway-service:
    restart: always
    container_name: fda-gateway-at.tuwien.service
    hostname: fda-gateway-at.tuwien.service
    build: ./fda-gateway-service
    image: fda-gateway-service
    network_mode: bridge
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 9095:9095
    links:
      - fda-discovery-server
      - fda-database-managing-service
      - fda-container-managing-service
      - fda-query-service
      - fda-table-service
    depends_on:
      - fda-discovery-server
      - fda-database-managing-service
      - fda-container-managing-service
      - fda-query-service
      - fda-table-service
    logging:
      driver: json-file

  fda-database-managing-service:
    restart: always
    container_name: fda-database-managing-at.tuwien.service
    hostname: fda-database-managing-at.tuwien.service
    build:
      context: ./fda-database-managing-service
    image: fda-database-managing-service
    network_mode: bridge
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 9092:9092
    links:
      - fda-discovery-server
      - fda-container-managing-service
    depends_on:
      - fda-discovery-server
      - fda-container-managing-service
    logging:
      driver: json-file

  fda-container-managing-service:
    restart: always
    container_name: fda-container-managing-at.tuwien.service
    hostname: fda-container-managing-at.tuwien.service
    build: ./fda-container-managing-service
    image: fda-container-managing-service
    network_mode: bridge
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 9091:9091
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - fda-discovery-server
    depends_on:
      - fda-discovery-server
    logging:
      driver: json-file

  fda-query-service:
    restart: always
    container_name: fda-query-at.tuwien.service
    hostname: fda-query-at.tuwien.service
    build: ./fda-query-service
    image: fda-query-service
    network_mode: bridge
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 9093:9093
    volumes:
      - /tmp:/tmp
    links:
      - fda-discovery-server
      - fda-container-managing-service
    depends_on:
      - fda-discovery-server
      - fda-container-managing-service
    logging:
      driver: json-file

  fda-table-service:
    restart: always
    container_name: fda-table-at.tuwien.service
    hostname: fda-table-at.tuwien.service
    build: ./fda-table-service
    image: fda-table-service
    network_mode: bridge
    environment:
      SPRING_PROFILES_ACTIVE: docker
      multipart.location: /tmp
    ports:
      - 9094:9094
    volumes:
      - /tmp:/tmp
    links:
      - fda-discovery-server
      - fda-query-service
      - fda-analyse-service
    depends_on:
      - fda-discovery-server

  fda-analyse-service:
    restart: always
    container_name: fda-analyse-at.tuwien.service
    hostname: fda-analyse-at.tuwien.service
    build: ./fda-analyse-service
    image: fda-analyse-service
    network_mode: bridge
    command: sh -c "/wait && flask run"
    environment:
      EUREKA_SERVER: http://fda-discovery-server:9090/eureka
      WAIT_HOSTS: fda-discovery-server:9090
      WAIT_HOSTS_TIMEOUT: 600
      WAIT_SLEEP_INTERVAL: 30
      WAIT_HOST_CONNECT_TIMEOUT: 30
    ports:
      - 5000:5000
    volumes:
      - /tmp:/tmp
    links:
      - fda-discovery-server
    depends_on:
      - fda-discovery-server
    logging:
      driver: json-file

  fda-ui:
    restart: always
    container_name: fda-ui
    hostname: fda-ui
    build: ./fda-ui
    image: fda-ui
    ports:
      - 3000:3000
    links:
      - fda-discovery-server
      - fda-container-managing-service
      - fda-query-service
      - fda-analyse-service
    depends_on:
      - fda-discovery-server
    environment:
      HOST: 0.0.0.0
      API_URL: //fda-database-managing-at.tuwien.service:9092/api
