#!/bin/bash
CERT_STORE_LOCATION="/tmp/cert.p12"
KEY_STORE_LOCATION="/tmp/dbrepo.jks"
KEY_STORE_PASS="dbrepo"
CERT_LOCATION="/etc/letsencrypt/live/dbrepo.ossdip.at"

# REQUEST
sudo certbot certonly --standalone --preferred-challenges http -d dbrepo.ossdip.at \
		-m martin.weise@tuwien.ac.at --agree-tos --keep-until-expiring

# CONVERT PKCS12
sudo openssl pkcs12 -export -out "${CERT_STORE_LOCATION}" -in "${CERT_LOCATION}/cert.pem" \
  -inkey "${CERT_LOCATION}/privkey.pem" -passout "pass:${KEY_STORE_PASS}"

# FIX PERMISSIONS
sudo chmod 644 "${CERT_STORE_LOCATION}"

# IMPORT
keytool -importkeystore -deststorepass "${KEY_STORE_PASS}" -destkeypass "${KEY_STORE_PASS}" \
  -destkeystore "${KEY_STORE_LOCATION}" -srckeystore "${CERT_STORE_LOCATION}" -srcstoretype PKCS12 \
  -srcstorepass "${KEY_STORE_PASS}" -alias 1