spring:
  main.banner-mode: off
  datasource:
    url: jdbc:postgresql://fda-metadata-db:5432/fda
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
  application:
    name: fda-database-managing-service
  cloud:
    loadbalancer.ribbon.enabled: false
server.port: 9092
logging:
  pattern.console: "%d %highlight(%-5level) %msg%n"
  level:
    org.springframework.web: warn
    guru.springframework.controllers: warn
    org.hibernate: warn
    at.tuwien.: info
eureka:
  instance.hostname: fda-database-managing-service
  client.serviceUrl.defaultZone: http://fda-discovery-server:9090/eureka/