spring:
  main.banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/fda
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
  application:
    name: fda-data-service
  cloud:
    loadbalancer.ribbon.enabled: false
server.port: 9098
logging:
  pattern.console: "%d %highlight(%-5level) %msg%n"
  level:
    root: warn
    at.tuwien.: debug
    at.tuwien.service.QueryService: trace
    at.tuwien.config.: trace
eureka:
  instance.hostname: fda-data-service
  client.serviceUrl.defaultZone: http://localhost:9090/eureka/
fda:
  gateway.endpoint: http://localhost:9095
  ready.path: ./ready