#!/bin/bash
CA_PATH="/etc/letsencrypt/live/docker.ossdip.at"
CERT_PATH="/home/rocky/registry/certs/"
USER="rocky"

sudo certbot certonly --standalone --preferred-challenges http -d docker.ossdip.at \
                -m martin.weise@tuwien.ac.at --agree-tos --keep-until-expiring

sudo cp "${CA_PATH}/fullchain.pem" "${CERT_PATH}"
sudo cp "${CA_PATH}/privkey.pem" "${CERT_PATH}"

sudo chown -R "${USER}:docker" "${CERT_PATH}"

ls -la "${CERT_PATH}"
