#!/bin/fish
docker-compose down
docker container stop (docker container ls -aq)
docker container rm (docker container ls -aq)
docker-compose build fda-metadata-db
docker-compose build
docker volume rm (docker volume ls -q)
