
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
    register-with-eureka: true
    fetch-registry: true
server:
  port: 9095
spring:
  application:
    name: fda-gateway-service
