#!/bin/bash
HOST_COUNT=$(rabbitmqctl status --quiet | grep -o "Virtual host count: \d*" | grep -o "\d*")
if [ $HOST_COUNT -ge 1 ]; then
  echo "service is ready and accepting connections"
  exit 0
fi
exit 1