spring:
  main.banner-mode: off
  datasource:
    url: jdbc:postgresql://fda-metadata-db:5432/fda
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
  application:
    name: fda-discovery-service
server.port: 9090
logging:
  pattern.console: "%d %highlight(%-5level) %msg%n"
  level:
    root: warn
    at.tuwien.: debug
eureka:
  eureka.client.register-with-eureka: false
  eureka.client.fetch-registry: false
  instance.hostname: fda-discovery-service
  client.serviceUrl.defaultZone: http://fda-discovery-service:9090/eureka/
fda:
  ready.path: /ready