spring:
  main.banner-mode: off
  datasource:
    url: jdbc:postgresql://fda-metadata-db:5432/fda
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
  application:
    name: fda-authentication-service
  cloud:
    loadbalancer.ribbon.enabled: false
server:
  port: 9097
logging:
  pattern.console: "%d %highlight(%-5level) %msg%n"
  level:
    root: warn
    at.tuwien.: debug
eureka:
  instance.hostname: fda-authentication-service
  client.serviceUrl.defaultZone: http://fda-discovery-service:9090/eureka/
fda:
  ready.path: ./ready
jwt:
  issuer: fda-dbrepo
  secret: fda-secret
  expiration.ms: 86400000