spring:
  main.banner-mode: off
  datasource:
    url: jdbc:postgresql://fda-metadata-db:5432/fda
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
  application:
    name: fda-authentication-service
  cloud:
    loadbalancer.ribbon.enabled: false
  security:
    saml2:
      metadata: https://dev-13953915.okta.com/app/exk26nye6eBAomvJW5d7/sso/saml/metadata
      base-url: https://dbrepo.ossdip.at:9097
      relyingparty:
        registration:
          okta-saml:
            signing:
              credentials:
                - private-key-location: "classpath:saml/saml_sign_priv.key"
                  certificate-location: "classpath:saml/saml_sign_public.cer"
            identityprovider:
              entity-id: https://www.okta.com/exk26nye6eBAomvJW5d7
              metadata-uri: https://dev-13953915.okta.com/app/exk26nye6eBAomvJW5d7/sso/saml/metadata
              verification.credentials:
                - certificate-location: "classpath:ssl/okta.crt"
              sso-url: https://dev-13953915.okta.com/app/dev-13953915_testtusaml_1/exk26nye6eBAomvJW5d7/sso/saml
              singlesignon.sign-request: true
server:
  port: 9097
  name: dbrepo.ossdip.at
  ssl:
    enabled: true
    key-alias: 1
    key-store: classpath:ssl/dbrepo.p12
    key-store-password: dbrepo
    key-store-type: pkcs12
logging:
  pattern.console: "%d %highlight(%-5level) %msg%n"
  level:
    root: warn
    at.tuwien.: debug
eureka:
  instance.hostname: fda-authentication-service
  client.serviceUrl.defaultZone: http://fda-discovery-service:9090/eureka/
fda:
  ready.path: /ready