spring:
  main.banner-mode: off
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  application:
    name: fda-authentication-service
  cloud:
    loadbalancer.ribbon.enabled: false
saml2:
  network:
    read-timeout: 10000
    connect-timeout: 5000
  service-provider:
    entity-id: at:tuwien
    sign-metadata: true
    sign-requests: true
    want-assertions-signed: true
    single-logout-enabled: true
    name-ids:
      - urn:oasis:names:tc:SAML:2.0:nameid-format:persistent
      - urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
      - urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified
    keys:
      active:
        name: saml
        private-key: |
          -----BEGIN ENCRYPTED PRIVATE KEY-----
          MIIJnDBOBgkqhkiG9w0BBQ0wQTApBgkqhkiG9w0BBQwwHAQIh2ZPgD3mFCQCAggA
          MAwGCCqGSIb3DQIJBQAwFAYIKoZIhvcNAwcECCFe/ygPmXGYBIIJSEqLBljzZBUp
          QRI4DGXaamfXVdkdaTHXbCL0Y4myyvaDklgl5o0Vr17vPdPe2kLfD4JQk7ercyiU
          QXYSov8MDOM98U75UazqzPb+duMhj4iPzCYvCX1ixPJPr/9xH6ZaQ70dczaxaciF
          lyt0QnVQJT2+k69BWwkV1mOBPb6+OCIjww/jmg9j7bAN3liTPtwJQ3D6XRVrx63U
          cZeXTcNcbFDl48PsA46YhYUatWSM+pBxJduwL6JiBToUoVxnxJJME0F9IUIE9AGB
          b/kVE5U9FMOLyoCRfvW5l+1DEMcjt0K/YV/fTVdIbkavcrUAXLGsPDSq/yLgmW/7
          VYmW7/wqrlDrM7hzuNOlo9E5qsTbvRL6A4wffnx4+lEvPT1gfCI7YaOD2kFfCNw8
          Qh1JjNAOrAw50FGbt/jz13TjEyNWK3uRgwzTcaer3uBV+xnEKlCh+IJzV62tZL4I
          Yv/XoX1H7XLMF+Bszf5M5eGpI5OKQ9Fufg5dhL/TQpYtTwpUpg5ch0TyiBGG4m6u
          BYgatwxPf1DKmrVgx3zteFwwtdp+cicgBFftV1uKWpFEb3umr7TKW3fX7opplfQd
          p4kOUHNFCUy0IyJFP0yA4uKVi4ci4VLlb02F+CIHR/YgLdtEwMY7oxmX1V+8u6Wu
          8JutnrswslV1rTqeUtT3RTJckBMaLfYf/UZArqIYwG9jIWfyeBqRZsTH3O9N4STf
          bt0lpJiOZRXAM1d4ynokZvXhViTuTniJKfs/qOhO7L0kxhRGQRh41ps8eyj3/r8/
          MYN0IBzKP2QAh0cN30pi2stutb5Yw+l6MZfFyvQqkAWkxZ55qWRVHyDW/cgYal0p
          +TrPCapEl2hHqG9mlos/Ozmu6nLkmGVBTI++F9gXoezYl0loZQ2HEETl7N05HTvg
          0otvBbk1avoUs5eucEOmrAaPWLuTXJ/6oxubu4Bl9KOaKNQDLT/Kzp89LlBMZpYT
          uOO+670RxOkBu2e4hZhMHwK/mTQ3B3Bbm02OLUSelJAend7lZwyqlcEapYDa7c7Q
          Fi9baO9jbSaU11R6wFLR4xst/x62RuXtIh4KqjCs/RSPPNN4CwITm8Y+xGGrx5Iz
          8G+mkb0ZFZxOysYpBeUV91ehGMs7OY6yQnfitfSRaeUjJyKO2r1HPiHDs9cxEPtn
          mBSn1WkAWtz+drPLkFwy2fThziZgoesYky+oiTJOGa/tUBoK7lN4+KtwejXexQGg
          6z5MBMx4Je8auOb3Dl1efZw6o5/s6WpmrE+DKs8fbda0oU2JJbbVSbhim59HoWje
          wssPF3aBo2RGRUs/3vSNh57Ntz5W8xfHV0ksmcrKCsRu4mKLfuhVk+FwASUHuurr
          Bb82cOF2f8TFecJAMijx8R4jktRtARSoyZ4EbQq5HipCjKC7ami0A5fKVL2s0VFC
          ua7uu68BFMFtEE+AJGAUlIbAip7Uc3kxnbd8d+om4pw4pQEmB11ojs1gPDFJ2j9H
          t1aroZcDtJEh53pKlqncrqi6o6tmqj2ZrVmpzxJSjnHFQXwte0p/MiECWknxw9ZL
          AOuDTM5x5Pj2/IqT/UK21gFXxCTD6zpUEevjbgp6vLJrNOo3Z+qgKr9v5DtTbXjh
          3iJ5SSeZSxBuIPPblJXkwBi4g9MPy1FK1c/rWYg/CSRqMpu6ljuJegBMkA8IMiqT
          dqYYojrh18dcvbMqw7ZJIyMCcdL73QH/Dl6e4ztX4F7WuIzC8Ws6op1Ol4F80Hjz
          +eIScC3YwC98UOupfmu0+W3YuKdW6xD50cnFD7aBcTB5KwNbr+O2AkLXUQTmWgdD
          n+OnmZcdWX+1YcNF0krpMmv4Y0eVhkTWQxmHRV6gUm//QaNxRPcxYpymLVRx5Q2h
          PCqIXPMLrDDDr+8HPhmCKdTLxNMiDAfLk4miMSNOQptXrWe+1UjYNzXWSVZQMwly
          nGHtX8TgYWFdtvtrNWmFdoCFhq/eN6rXOLBJAwt8sYS7xX6JVsqfgMyCoY9xi3y1
          IoRvi+2NbRt3M+gVJ+g+ak1yZwMuwCTf0QM6eM3HH2Z97qtYDu+2BRCSzYTPRFud
          0ji97x37Skj6u8gJ1aTV5gh6T02Vs+4y/eDwR7EZvWsgPcD9L+wmDSn4X4C6AIPs
          QhCepSKV1mJeeaXGLCjmJMiQP5+QKxNfYEOsuYyU1w+m0mLYCKQx+IImNVJo/YPP
          V4dxxaK+x5T1G2BHJ+Hyc+5NAh+S9t2F1Ci+X44wEGg4JdyHnr1JOYShqoKh+uAN
          ul2BkaOPrGw6u+7EKBTcAcyRfSEk3yTtSQ6dmqYUdsmYJpT+2jMorq3NB02kYNGZ
          5PXfwvnkxqs0pRqAvofT1js5RhDi7bHr7YZx64l/7WCucZ/xMZYqFKjv3z3bDnPt
          lgvY7qPrI3k5TFIrV9kIKD4iVEXVIo17p77ML1EIcwfihCteX2kZzj1FHrw2JuLP
          XR9tqBJ16A33+Yoyg2AdpC207FtjAR6b2VVyYSEGptmjED618atr7tI+cf28360+
          NfPMIHy9E+XBtDu+7/3aJgE8mmZnqx+bT0P7x7ZVS44oR/Qdcrs/6jQ9IS0/kGfG
          19nhQrW+UeZtCG6eI7RlPjdGgdcGgL7M63LUOSKJYES6sFnwt1bTYZ/RZtYybRb+
          /RVqn68pS1mC2PZB9fhDsXB7gyg1aKgK1CjfRAwww1rxoqRJq2DjtYVqMLLOKbik
          5opm3JkrjBkDheUe2qJWtToec9zxwxrMjchGtUT6Y0Twclv/WV8MgjEXtypGuG1Y
          WTmRy+yahi/PEXDE/a4pZaqLQIcfDbFwiOjzmV04AZgGbRYKzAW9eSOZoZf7eYxp
          ZfUvIVHXc95xSTN5JCSK5FmGUBSj8r3W9Fe12tXkW/ka3WENOVbnR2Ay7JV253zh
          SaUtRhkI2atbIPtWK9bbud4wtX7YicNlIukkBfI7VaUBdoht65uSp0VuNezE3+qh
          thVCdqqFkqN3fCj3Fu63vJSIJQXA9u298nAMqOOEnAKVcIYmeSQqqjm9jjhLTBCi
          eB0ovwpKv5xtKtsdLFx0tabBgvHgjO0kJPOnkUPqDgbEIRJhGbo3ETH6XKnzTrs7
          bVYZFOVSeJB4lAkBea8TmjHTCuLXAyBWcpZX9e4uMLbqvKwbgq9umIwt4wjxUL8v
          r6Fsd8D1f79LRxkg5dM+pg==
          -----END ENCRYPTED PRIVATE KEY-----
        passphrase: "${SAML_SIGN_PASSWORD}"
        certificate: |
          -----BEGIN CERTIFICATE-----
          MIIGVTCCBD2gAwIBAgIUX+IqATTsZiVivn6etfKiy8KxHUEwDQYJKoZIhvcNAQEL
          BQAwgbkxCzAJBgNVBAYTAkFUMQ8wDQYDVQQIDAZWaWVubmExDzANBgNVBAcMBlZp
          ZW5uYTEQMA4GA1UECgwHVFUgV2llbjExMC8GA1UECwwoWmVudHJ1bSBmw4PCvHIg
          Rm9yc2NodW5nc2RhdGVubWFuYWdlbWVudDEZMBcGA1UEAwwQZGJyZXBvLm9zc2Rp
          cC5hdDEoMCYGCSqGSIb3DQEJARYZbWFydGluLndlaXNlQHR1d2llbi5hYy5hdDAe
          Fw0yMTExMjgxNzE0NDBaFw0yMjExMjgxNzE0NDBaMIG5MQswCQYDVQQGEwJBVDEP
          MA0GA1UECAwGVmllbm5hMQ8wDQYDVQQHDAZWaWVubmExEDAOBgNVBAoMB1RVIFdp
          ZW4xMTAvBgNVBAsMKFplbnRydW0gZsODwrxyIEZvcnNjaHVuZ3NkYXRlbm1hbmFn
          ZW1lbnQxGTAXBgNVBAMMEGRicmVwby5vc3NkaXAuYXQxKDAmBgkqhkiG9w0BCQEW
          GW1hcnRpbi53ZWlzZUB0dXdpZW4uYWMuYXQwggIiMA0GCSqGSIb3DQEBAQUAA4IC
          DwAwggIKAoICAQCamfgFkEkCLdt9DI3ceV1HshLW9KsLSAqCUfMmRaa+xk6Q8bc6
          h9TMBcCkWHi6uAi/467cOWytxxCEfxiwhu1QRToX3vxRa86rrk5tTrX7BVeWAjka
          +VgtANtDkpdKvhNCKzpOTjePRJ3lIv0v+UvOZaWxQnqNkal+dJgqcESVlSCePuxl
          1KKe2cz3VqnydbJiXCETiknYFPoHRZhWX4yYzOY5e/divwi+Raadg6jL9iwzqFMC
          kYozZSNLtvlFm2NnQeicxVMgLS9COkE4p499uiX0zWKnISHxVSrbSK6/aqXGBDU0
          Xt/UNG9y3/AJUIWkdMQ4FQDAZu9P1MwWzrHNfRgDIf4VeK5xf3CY5YibUrfYWoXS
          xs/U7L/FwzecScsSlPM/h3BgB0JiSGl5kLWnjhn95FWVYEYZlT95P3/M3hmNaJ9s
          G1gsv9sXV6J70qGnkCmaY9ZrMiQBzPYn1ljtPaQjXZumAvueq7tFI9xoeEXfUE6z
          GxwQSVmYf3fH/ssJoOn8fJdl6FSEVHH+4IyHJqJjtVhhVwcz3gtNnTiAjQsgImkj
          e7GFwKYxdPut73TfWuAPhSq1IS/yCOm4LbxIG2MF8jmXKS/Y9D5suMwMaOAShL6t
          zFlhdvaoTGlGNBmQR787WFthr/lZm6kUb761bYT8M3UfZzEHVijts5fPzwIDAQAB
          o1MwUTAdBgNVHQ4EFgQUxvKTYCI3VKyE+pgU1hCGz/feF94wHwYDVR0jBBgwFoAU
          xvKTYCI3VKyE+pgU1hCGz/feF94wDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0B
          AQsFAAOCAgEAFmFXEXrZgs5ckoWyXBc8Fe14QR4SqspxyfuZmIGN7hiQtNKCO6TU
          NUipdo8laFAFC5JAo2x6bVXabMjdB7JGWi9JdthBWjLVGOtV9uty5K6jPLU/6nwa
          29eotrK389g9sh60FYC0LcyVQu4i6jf9ccZOfHAqWbMwDfogu9yNA8yMYkQBtxB0
          xKmg7sveIkH1jixLI5ZbQwRcWguLLXhLppoPROH3yNwWbZ44NjcAyOH90NC5x6xU
          ITx3QnItxq4MCgQ+NHcg1FbcIaRbTdJXcBpbjwFFbOVc0vtIbUXarkeDpv6Aaqmp
          R4pI/sx0CUgy8HUxXH+Nb49oCvZtkRLkja2E4TmaGTBwSMy6wJT6VBCJZmCiO36P
          TgiwQk9OCX4oilX//to4gtGiPo8zlIE7a9QFIHpJeLTMmmv9gt1hCHvf1CxSn476
          tc3kVJefGJu7F5xoL7XyRdTWqP6He3rPRgx9S6DSxWwPKdw5xOao747IX5l8dAQq
          cNWwC9C2xj8FdnG8dPtS/zMurXElmbAgSnTXbX9f+hgabFSqraK+JLxIYO5SaAUV
          ggPfZdUBg6RFDQAgTSXbbRaNR85pA0yMHRIL7TMga89+/iRqGKYL0xJxtEHt7Elp
          Ec2c2LjZdbgFCBLeX2R/lYs7JUnwESJSP7kLZwcwJqDyga1ldWiWah4=
          -----END CERTIFICATE-----
    providers:
      - entity-id: at:tuwien
        metadata: https://idp.zid.tuwien.ac.at/saml2
        link-text: TU Wien IdP Application
        alias: tu
server:
  port: 9097
  ssl:
    enabled: true
    key-alias: ssl
    key-store: file:/tmp/dbrepo.jks
    key-store-password: "${KEY_STORE_PASSWORD}"
    key-store-type: jks
logging:
  pattern.console: "%d %highlight(%-5level) %msg%n"
  level:
    root: warn
    org.springframework.security.saml.: debug
    at.tuwien.: debug
eureka:
  instance.hostname: fda-authentication-service
  client.serviceUrl.defaultZone: http://fda-discovery-service:9090/eureka/
fda.ready.path: /ready