spring:
  main.banner-mode: off
  application:
    name: fda-authentication-service
  cloud:
    loadbalancer.ribbon.enabled: false
server.port: 9097
logging:
  pattern.console: "%d %highlight(%-5level) %msg%n"
  level:
    root: warn
    at.tuwien.: debug
eureka:
  instance.hostname: fda-authentication-service
  client.serviceUrl.defaultZone: http://localhost:9090/eureka/