spring:
  main.banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/fda
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
  application:
    name: fda-authentication-service
  cloud:
    discovery.enabled: false
    loadbalancer.ribbon.enabled: false
  security:
    saml2:
      metadata: https://dev-13953915.okta.com/app/exk26nye6eBAomvJW5d7/sso/saml/metadata
      base-url: https://localhost:9097
      relyingparty:
        registration:
          okta-saml:
            identityprovider:
              entity-id: http://www.okta.com/exk26nye6eBAomvJW5d7
              verification.credentials:
                - certificate-location: "classpath:ssl/okta.crt"
              singlesignon.url: https://dev-13953915.okta.com/app/dev-13953915_testtusaml_1/exk26nye6eBAomvJW5d7/sso/saml
              singlesignon.sign-request: false
server:
  port: 9097
  ssl:
    enabled: true
    key-alias: dbrepo
    key-store: classpath:saml/dbrepo.p12
    key-store-password: dbrepo
    key-store-type: pkcs12
  error:
    whitelabel:
      enabled: false
logging:
  pattern.console: "%d %highlight(%-5level) %msg%n"
  level:
    root: warn
    at.tuwien.: debug
eureka:
  instance.hostname: fda-authentication-service
  client.serviceUrl.defaultZone: http://localhost:9090/eureka/
fda:
  ready.path: ./ready