#!/bin/bash

USER="fairdataaustria"
VERSION=$1

# usage
if [ $# -ne 1 ]; then
  echo "USAGE: ./release VERSION"
  echo "                 (e.g. 1.0.0-alpha)"
  exit 1
fi

# build
git checkout master
docker-compose build fda-metadata-db
docker-compose build --parallel

# login
echo "Authentication required for user ${USER} at docker.io (docker hub)"
docker login docker.io -u $USER

# tag
IMAGES=$(ls -d fda-*)
for IMAGE in $IMAGES
do
  echo "TAG ${DIR} (local) ${IMAGE}:latest (remote) ${USER}/${IMAGE}:${VERSION}"
  docker tag "${IMAGE}:latest" "${USER}/${IMAGE}:${VERSION}"
  docker push "${USER}/${IMAGE}:${VERSION}"
done
