spring:
  main.banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/fda
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  application:
    name: fda-table-service
  cloud:
    loadbalancer.ribbon.enabled: false
server.port: 9094
logging:
  pattern.console: "%d %highlight(%-5level) %msg%n"
  level:
    root: warn
    at.: debug
eureka:
  instance.hostname: fda-table-service
  server:
    peer-node-read-timeout-ms: 200
  client.serviceUrl.defaultZone: http://localhost:9090/eureka/
fda:
  mapping.path: rest-service/src/main/resources
  table.path: rest-service/src/main/java/at/tuwien/userdb