spring:
  main.banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/fda
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
  application:
    name: fda-table-service
  rabbitmq:
    host: fda-broker-service
    username: guest
    password: guest
  cloud:
    loadbalancer.ribbon.enabled: false
server.port: 9094
logging:
  pattern.console: "%d %highlight(%-5level) %msg%n"
  level:
    root: warn
    at.tuwien.: debug
    at.tuwien.service.: trace
eureka:
  instance.hostname: fda-table-service
  client.serviceUrl.defaultZone: http://localhost:9090/eureka/
fda:
  mapping.path: rest-service/src/main/resources
  table.path: rest-service/src/main/java/at/tuwien/userdb