#!/bin/bash
CA_PATH="/etc/letsencrypt/live/dbrepo.ossdip.at"
CERT_PATH="./fda-ui/.prod/"
USER="rocky"

if [ "$ENV" != "prod" ]; then
  echo "WARN: environment must be prod"
  exit 0
fi

sudo certbot certonly --standalone --preferred-challenges http -d dbrepo.ossdip.at \
                -m martin.weise@tuwien.ac.at --agree-tos --keep-until-expiring

sudo cp "${CA_PATH}/cert.pem" "${CERT_PATH}"
sudo cp "${CA_PATH}/privkey.pem" "${CERT_PATH}"

mv ./fda-ui/secure.conf ./fda-ui/.prod/default.conf

mkdir -p "${CERT_PATH}"
sudo chown -R "${USER}:docker" "${CERT_PATH}"

ls -la "${CERT_PATH}"
