package at.tuwien.api.database.table.columns;

import at.tuwien.api.container.image.ImageDateDto;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import lombok.*;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

@Getter
@Setter
@ToString
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class ColumnDto {

    @NotNull
    @ApiModelProperty(name = "id", example = "1", required = true)
    private Long id;

    @NotBlank
    @ApiModelProperty(name = "name", example = "Date", required = true)
    private String name;

    @NotBlank
    @JsonProperty("internal_name")
    @ApiModelProperty(name = "internal name", example = "mdb_date", required = true)
    private String internalName;

    @NotBlank
    @JsonProperty("date_format")
    @ApiModelProperty(name = "date format", example = "1")
    private ImageDateDto dateFormat;

    @NotNull
    @JsonProperty("auto_generated")
    @ApiModelProperty(name = "column autogenerated", example = "false")
    private Boolean autoGenerated;

    @NotNull
    @JsonProperty("is_primary_key")
    @ApiModelProperty(name = "primary key", example = "true", required = true)
    private Boolean isPrimaryKey;

    @NotNull
    @JsonProperty("column_type")
    @ApiModelProperty(name = "type", example = "STRING", required = true)
    private ColumnTypeDto columnType;

    @NotNull
    @ApiModelProperty(name = "unique", example = "true", required = true)
    private Boolean unique;

    @NotNull
    @JsonProperty("is_null_allowed")
    @ApiModelProperty(name = "null allowed", example = "true", required = true)
    private Boolean isNullAllowed;

    @JsonProperty("check_expression")
    @ApiModelProperty(name = "check constraint", example = "Price Limit > 0", hidden = true)
    private String checkExpression;

    @JsonProperty("foreign_key")
    @ApiModelProperty(name = "foreign key", hidden = true)
    private String foreignKey;

    @ApiModelProperty(name = "foreign key reference, only considered when foreignKey != null", example = "null")
    private String references;

    @JsonProperty("enum_values")
    @ApiModelProperty(name = "enum values, only considered when type = ENUM", example = "[\"male\",\"female\",\"other\"]")
    private String[] enumValues;

}
