package at.tuwien.api.database.table.columns;

import io.swagger.annotations.ApiModelProperty;
import lombok.*;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

@Getter
@Setter
@ToString
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class ColumnDto {

    @NotBlank
    @ApiModelProperty(name = "name", example = "Date", required = true)
    private String name;

    @NotBlank
    @ApiModelProperty(name = "internal name", example = "mdb_date", required = true)
    private String internalName;

    @NotBlank
    @ApiModelProperty(name = "date format", example = "YYYY-mm-dd")
    private String dateFormat;

    @NotNull
    @ApiModelProperty(name = "column autogenerated", example = "false")
    private Boolean autoGenerated;

    @NotNull
    @ApiModelProperty(name = "primary key", example = "true", required = true)
    private Boolean isPrimaryKey;

    @NotNull
    @ApiModelProperty(name = "type", example = "STRING", required = true)
    private ColumnTypeDto columnType;

    @NotNull
    @ApiModelProperty(name = "unique", example = "true", required = true)
    private Boolean unique;

    @NotNull
    @ApiModelProperty(name = "null allowed", example = "true", required = true)
    private Boolean isNullAllowed;

    @ApiModelProperty(name = "check constraint", example = "Price Limit > 0", hidden = true)
    private String checkExpression;

    @ApiModelProperty(name = "foreign key", hidden = true)
    private String foreignKey;

    @ApiModelProperty(name = "foreign key reference, only considered when foreignKey != null", example = "null")
    private String references;

    @ApiModelProperty(name = "enum values, only considered when type = ENUM", example = "[\"male\",\"female\",\"other\"]")
    private String[] enumValues;

}
